original_repo: https://github.com/hackcu/blueprint
title: HackCU Blueprints
color: "#2E3561"

collections:
  pages:
    output: true
    permalink: /:path/

sass:
    sass_dir: assets/_sass
    style: compressed

plugins:
  - jemoji